version: '3'

services:
  db:
    container_name: go_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shopdevgo
    ports:
      - '3306:3306'
    networks:
      - app-network

  redis:
    image: 'redis:latest'
    container_name: 'go_redis'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
